id: P70BF3062
initial_creation_type: input
source_metadata:
  title: The Mirror Illuminating the Royal Genealogies
  author: བླ་མ་དམ་པ་བསོད་ནམས་རྒྱལ་མཚན།
  description: 'Digital version 1.0 {Tibetan}; master xml (completed: 2020-02-02);
    revision in process, no thematic TEI markup'
  source: https://sakyaresearch.org
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།; This text was published by the Sa skya'i
    dpe rnying bsdu sgrig u lhan. (src)
  - Text input:unspecified
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:ས་སྐྱའི་དཔེ་རྙིང་བསྡུ་སྒྲིག་ཨུ་ལྷན། (eds)
  text_witnesses: https://sakyaresearch.org/sources/3829
  bases:
    7dcd:
      title: The Mirror Illuminating the Royal Genealogies
      order: 1
      base_file: 7dcd.txt
created_at: '2022-04-15T18:53:13.155812'
last_modified_at: '2022-04-15T18:53:13.155819'
quality: null
